loan <- read.csv(file.choose(), header = TRUE, sep = ",")
head(loan)
summary(loan)
str(loan)
loan$AGE <- as.factor(loan$AGE)
model1 <- glm(DEFAULTER ~ ., family = binomial, data = loan)
summary(model1)
null <- glm(DEFAULTER ~ 1, family = binomial, data = loan)
anova(null, model1, test = "Chisq")
loan$predprob <- round(fitted(model1), 2)
head(loan)
library(ROCR)
pred <- predict(model1, loan, type = "response")
rocrpred <- prediction(pred, loan$DEFAULTER)
rocrperf <- performance(rocrpred, "tpr", "fpr")
plot(rocrperf, colorize = TRUE, print.cutoffs.at = seq(0.1, by = 0.1))
auc <- performance(rocrpred, measure = "auc")
auc_value <- auc@y.values[[1]]
print(auc_value)
coef(model1)
exp(coef(model1))

library(ROCR)
data(mtcars)
split <- sample.split(mtcars, SplitRatio = 0.8)
train <- subset(mtcars, split == TRUE)
test <- subset(mtcars, split == FALSE)
model<-glm(vs~wt+disp+hp,family = binomial,data=train)
pred<-predict(model,test,type="response")
pred<-ifelse(pred>0.5,1,0)
roc_pred<-prediction(pred,test$vs)
roc_perf<-performance(roc_pred,"tpr","fpr")
plot(roc_perf,colorize=TRUE,print.cutoffs.at=seq(0,1,0.1))
performance(roc_pred,"auc")@y.values[[1]]

data(Titanic)
data<-data.frame(Titanic)
model <- glm(Survived ~ Class + Sex + Age, family = binomial, data = data)
summary(model)
predictions <- predict(model, type = "response")
library(ROCR)
prediction_objects <- prediction(predictions, data$Survived)
roc_object <- performance(prediction_objects, "tpr","fpr")
plot(roc_object, main = "ROC Curve", col = "blue", lwd = 2)
performance(prediction_objects, measure = "auc")@y.values[[1]]
